version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../deploy:/app/../deploy:ro
    environment:
      - FLASK_ENV=production
    restart: unless-stopped 