version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../deploy:/app/../deploy:ro
    environment:
      - FLASK_ENV=production
    restart: unless-stopped 
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: acme_store
      MYSQL_USER: acmeuser
      MYSQL_PASSWORD: acmepass
    ports:
      - "3306:3306"
    volumes:
      - ../deploy/init.sql:/docker-entrypoint-initdb.d/init.sql:ro 